import React from 'react';

import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Auth',
  description: 'Generated by create next app',
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="h-full bg-gray-100">{children}</div>
  );
}
